Repository knative/website, pull requests merged in 2019-08, with the labels that each got.

#62 Improve build scripts
  config/_default/config.toml
  config/_default/params.toml
  config/production/config.toml
  config/staging/config.toml
  i18n/en.toml
  layouts/partials/page-meta-links.html
  scripts/build.sh
  scripts/docs-version-settings.sh
  scripts/localbuild.sh
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#66 Make titles show - fix index.md and _index.md conflict
  config/_default/params.toml
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/S

#67 make sure to skip the main landing page
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/XS

#69 fix security vulnerability - lodash to 4.17.15
  package-lock.json
  package.json
Labels: approved, cla: yes, lgtm, size/XS

#70 add main page to local builds
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/S

#71 add a shortcode to dynamically or manually specify a version #
  layouts/shortcodes/version.md
Labels: approved, cla: yes, lgtm, size/S

#73 fix ignore file config and force inpage toc option
  config/_default/config.toml
  layouts/partials/landingtoc.html
Labels: approved, cla: yes, lgtm, size/M

#74 dynamic branch names for code samples
  layouts/shortcodes/branch.md
  layouts/shortcodes/version.md
Labels: approved, cla: yes, size/S

#63 Add support for "including code" into our docs
  layouts/shortcodes/readfile.md
Labels: approved, cla: yes, size/L

#78 Include the development and v0.#-docs dir too
  config/_default/config.toml
Labels: approved, cla: yes, lgtm, size/XS

#80 prevent netlify from processing whitespace as codeblocks
  layouts/shortcodes/readfile.md
Labels: approved, cla: yes, lgtm, size/S

#82 ignore development content
  layouts/shortcodes/version.md
Labels: approved, cla: yes, lgtm, size/S

#75 [WIP] v0.8 add /build/ redirects for removed files
  netlify.toml
Labels: approved, cla: yes, lgtm, size/XS

#72 localbuild.sh fix - add missing step
  scripts/localbuild.sh
Labels: approved, cla: yes, lgtm, size/S

#79 Remove "Knative Build" from the main page
  content-override/en/_index.html
Labels: approved, cla: yes, lgtm, size/S

#81 Fix typo on index page
  content-override/en/_index.html
Labels: approved, cla: yes, lgtm, size/XS

#77 Add v0.8 to knative.dev doc builds
  config/_default/params.toml
  scripts/docs-version-settings.sh
  scripts/localbuild.sh
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/S

#83 default pre-release to latest version
  layouts/shortcodes/version.md
Labels: approved, cla: yes, lgtm, size/XS

#86 narrow grep search for PR fork name
  scripts/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#87 Fix the fork name search
  scripts/build.sh
Labels: approved, cla: yes, lgtm, size/S
