Repository knative/website, pull requests merged in 2019-04, with the labels that each got.

#20 global params and other fixes
  config/_default/params.toml
  layouts/partials/navbar-version-selector.html
  layouts/partials/navbar.html
  layouts/partials/page-meta-links.html
  layouts/partials/sidebar-tree.html
Labels: approved, lgtm, size/L

#22 fix typo in var names
  layouts/partials/navbar.html
  layouts/partials/sidebar-tree.html
Labels: approved, lgtm, size/XS

#21 Update the main landing page with new layout and content
  assets/scss/_index.scss
  assets/scss/_nav.scss
  assets/scss/_variables.scss
  assets/scss/_variables_project.scss
  content-override/en/_index.html
  layouts/partials/community_links.html
  layouts/shortcodes/icon.html
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.json
  resources/_gen/images/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_960x540_fill_catmullrom_top_2.png
  scripts/build.sh
Labels: approved, lgtm, size/XXL

#26 UX fixes: Template overrides for readfile, feedback links, and last mod
  config/_default/config.toml
  config/_default/params.toml
  config/production/params.toml
  layouts/_default/content.html
  layouts/docs/list.html
  layouts/partials/landingtoc.html
  netlify.toml
Labels: approved, lgtm, size/M

#27 override pre tag - fix hor scrollbar overlap
  assets/scss/_code.scss
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.json
Labels: approved, lgtm, size/XXL

#29 add v0.5 docs to website
  config/_default/params.toml
  scripts/build.sh
Labels: approved, lgtm, size/S

#28 Fix link to "Documentation" from other sections
  config/_default/params.toml
  layouts/partials/navbar.html
  layouts/partials/sidebar-tree.html
Labels: approved, lgtm, size/M

#32 fix non docs link to github
  config/_default/params.toml
  layouts/partials/navbar-version-selector.html
  layouts/partials/navbar.html
  layouts/partials/page-meta-links.html
Labels: approved, lgtm, size/M

#33 link to Post to the knative.dev blog
  layouts/blog/list.html
  layouts/partials/blogrelatedlinks.html
  layouts/partials/blogwelcome.html
  layouts/partials/page-meta-links.html
Labels: approved, cla: yes, kind/enhancement, kind/template-mod, lgtm, size/L

#34 update CSE ID
  config/production/params.toml
Labels: approved, cla: yes, lgtm, size/XS

#35 Surface all samples on the Community page
  config/_default/params.toml
  layouts/partials/community_links.html
Labels: approved, cla: yes, lgtm, size/L

#36 remove duplicate link to blog
  config/_default/params.toml
Labels: approved, cla: yes, lgtm, size/S

#37 match default URL - fix github links
  config/_default/config.toml
Labels: approved, cla: yes, lgtm, size/XS

#38 add missing hugo resource files
  config/_default/params.toml
  resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.content
  resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.json
  resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.content
Labels: approved, cla: yes, lgtm, size/S
