Repository knative/website, pull requests merged in 2019-06, with the labels that each got.

#52 update hugo and node version, plus fix vulnerability
  netlify.toml
  package-lock.json
  package.json
Labels: approved, cla: yes, lgtm, size/L

#49 Updated the overall design for the Knative website.
  .gitignore
  assets/scss/_blog.scss
  assets/scss/_breadcrumb.scss
  assets/scss/_main-container.scss
  assets/scss/_nav.scss
  assets/scss/_sidebar-toc.scss
  assets/scss/_sidebar-tree.scss
  assets/scss/_variables.scss
  assets/scss/_variables_project.scss
  assets/scss/main.scss
  content-override/en/_index.html
  layouts/blog/baseof.html
  layouts/community/list.html
  layouts/docs/baseof.html
  layouts/partials/community_links.html
  layouts/partials/footer.html
  layouts/partials/navbar-version-selector.html
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
Labels: approved, cla: yes, lgtm, size/XL

#53 Fix the "readfile" to include the file's TOC
  layouts/shortcodes/readfile.md
Labels: approved, cla: yes, lgtm, size/XS

#58 Attempt to set up short links in netlify following Istio.
  static/_redirects
  static/golang/build.html
  static/golang/caching.html
  static/golang/client.html
  static/golang/eventing-contrib.html
  static/golang/eventing.html
  static/golang/observability.html
  static/golang/pkg.html
  static/golang/sample-controller.html
  static/golang/serving-operator.html
  static/golang/serving.html
  static/golang/test-infra.html
Labels: approved, cla: yes, lgtm, size/M

#59 Update build script to make 0.7 branch the default
  config/_default/params.toml
  resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.content
  resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.json
  resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.content
  resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.json
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
  resources/_gen/assets/svg/icons/logo.svg_d3f53f09220d597dac26fe7840c31fc9.content
  resources/_gen/assets/svg/icons/logo.svg_d3f53f09220d597dac26fe7840c31fc9.json
  scripts/build.sh
Labels: approved, cla: yes, lgtm, size/M

#60 ignore the local-build only 'resources' folder
  .gitignore
Labels: approved, cla: yes, lgtm, size/XS

#24 add licenses to footer
  config/_default/params.toml
  layouts/partials/footer.html
Labels: approved, cla: yes, lgtm, size/S
