Repository knative/website, pull requests merged in 2019-03, with the labels that each got.

#8 support relative paths in readfile + dynamic version selector
  assets/scss/_nav.scss
  config/_default/config.toml
  layouts/partials/navbar-version-selector.html
  layouts/partials/navbar.html
  layouts/partials/sidebar-tree.html
  layouts/shortcodes/readfile.html
  layouts/shortcodes/readfile.md
  resources/_gen/images/docs/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/docs/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/docs/content-en-docs/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/docs/content-en-docs/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_960x540_fill_catmullrom_top_2.png
Labels: approved, lgtm, size/L

#9 updating resources folder, build script, and build params
  assets/scss/_nav.scss
  config/_default/config.toml
  config/_default/params.toml
  config/production/config.toml
  config/staging/config.toml
  config/staging/params.toml
  package-lock.json
  resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.content
  resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.json
  resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.json
  resources/_gen/images/about/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_1920x1080_fill_q75_catmullrom_bottom.jpg
  resources/_gen/images/about/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_960x540_fill_q75_catmullrom_bottom.jpg
  resources/_gen/images/background_hu16caed3139cd52fb3a1e4f9232b87afc_22314_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu16caed3139cd52fb3a1e4f9232b87afc_22314_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu22a155ee26cb2918767d83f32314da50_14793_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu22a155ee26cb2918767d83f32314da50_14793_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu2809edbdf6d2d161568a127353822be3_15047_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu2809edbdf6d2d161568a127353822be3_15047_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu3b5d3c7d207e37dceeedd301e35e2e58_0_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu6215058fdc2f1e391014cabee604df24_20974_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu6215058fdc2f1e391014cabee604df24_20974_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu6ffdc30d0d666cca2cd2948ad32dd517_20390_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_hu6ffdc30d0d666cca2cd2948ad32dd517_20390_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_huaf8a462bd3ba8ca0264b38e4e3da56da_21761_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_huaf8a462bd3ba8ca0264b38e4e3da56da_21761_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_hubcbebf9ac6a78c0f7f904065950ef1ac_18736_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_hubcbebf9ac6a78c0f7f904065950ef1ac_18736_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_huc72bd6a92c8d2e987387f1a6857bbe89_25167_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_huc72bd6a92c8d2e987387f1a6857bbe89_25167_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_hude0d9c4a6f699e02a767220b4ba8c163_20700_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/background_hude0d9c4a6f699e02a767220b4ba8c163_20700_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_1920x1080_fill_box_top_2.png
  resources/_gen/images/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_1920x1080_fill_catmullrom_bottom_2.png
  resources/_gen/images/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_1920x1080_fill_catmullrom_center_2.png
  resources/_gen/images/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_960x540_fill_box_top_2.png
  resources/_gen/images/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_960x540_fill_catmullrom_bottom_2.png
  resources/_gen/images/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_960x540_fill_catmullrom_center_2.png
  resources/_gen/images/content/en/about/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_1920x1080_fill_q75_catmullrom_bottom.jpg
  resources/_gen/images/content/en/about/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_960x540_fill_q75_catmullrom_bottom.jpg
  resources/_gen/images/content/en/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_1920x1080_fill_q75_catmullrom_top.jpg
  resources/_gen/images/content/en/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_960x540_fill_q75_catmullrom_top.jpg
  resources/_gen/images/docs/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/docs/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/docs/content-en-docs/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_1920x1080_fill_catmullrom_top_2.png
  resources/_gen/images/docs/content-en-docs/background_huf84130b9047e955ecb9d9e297f47ecd1_20547_960x540_fill_catmullrom_top_2.png
  resources/_gen/images/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_1920x1080_fill_q100_catmullrom_top.jpg
  resources/_gen/images/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_1920x1080_fill_q75_catmullrom_center.jpg
  resources/_gen/images/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_1920x1080_fill_q75_catmullrom_smart1.jpg
  resources/_gen/images/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_1920x1080_fill_q75_catmullrom_top.jpg
  resources/_gen/images/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_960x540_fill_q100_catmullrom_top.jpg
  resources/_gen/images/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_960x540_fill_q75_catmullrom_center.jpg
  resources/_gen/images/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_960x540_fill_q75_catmullrom_smart1.jpg
  resources/_gen/images/featured-background_hudb90b37223d61d4baae90ceef1e1eda4_169808_960x540_fill_q75_catmullrom_top.jpg
  scripts/build.sh
Labels: approved, lgtm, size/XXL

#10 Update script to treat README.md files differently
  scripts/build.sh
Labels: approved, lgtm, size/S

#11 Remove ../../ to ../../../ conversion
  scripts/build.sh
Labels: approved, lgtm, size/XS

#12 Update website to include v3, v4, and master docs
  config/_default/params.toml
  scripts/build.sh
Labels: approved, enhancement, lgtm, size/M

#14 replace knative favicon
  layouts/partials/favicons.html
  static/images/favicon.ico
Labels: approved, lgtm, size/XS

#15 Remove white on favicon background
  static/images/favicon.ico
Labels: approved, lgtm, size/XS

#16 UX improvements to docs menu
  layouts/partials/navbar-version-selector.html
  layouts/partials/navbar.html
  layouts/partials/sidebar-tree.html
Labels: approved, lgtm, size/M

#19 show menu when viewport smaller than d-sm
  layouts/partials/navbar-version-selector.html
Labels: approved, lgtm, size/XS
