Repository knative/website, pull requests merged in 2019-12, with the labels that each got.

#107 Fix some nested content rendering issues
  netlify.toml
Labels: approved, cla: yes, lgtm, size/XS

#94 add new GA property ID to site config
  config/production/config.toml
Labels: approved, cla: yes, lgtm, size/XS

#111 Use vanity https://slack.knative.dev
  content-override/en/_index.html
Labels: approved, cla: yes, lgtm, size/XS

#112 release-0.11 updates to site
  config/production/params.toml
  netlify.toml
  scripts/docs-version-settings.sh
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/S

#110 Refine the GitHub to Hugo script
  config/_default/params.toml
  config/local/params.toml
  config/staging/params.toml
  layouts/shortcodes/readfile.md
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, kind/bug, lgtm, size/M

#115 upgrade to hugo 0.61.0 and use Goldmark processor
  config/_default/config.toml
  config/_default/markup.toml
  netlify.toml
Labels: approved, cla: yes, lgtm, size/M

#113 Update _redirects to include eventing-operator
  static/_redirects
Labels: approved, cla: yes, lgtm, size/XS

#116 Create eventing-operator.html
  static/golang/eventing-operator.html
Labels: approved, cla: yes, lgtm, size/XS
