Repository knative/website, pull requests merged in 2020-07, with the labels that each got.

#187 Add knative.dev/discovery golang redirect
  static/_redirects
  static/golang/discovery.html
Labels: approved, cla: yes, lgtm, size/XS

#190 Move knative/net-http01 to knative-sandbox
  static/golang/net-http01.html
Labels: approved, cla: yes, lgtm, size/XS

#189 Update config
  config/_default/params.toml
  config/local/params.toml
  config/production/params.toml
  config/staging/params.toml
  netlify.toml
  scripts/docs-version-settings.sh
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/M

#192 Update OWNERS to remove ex-Knativists and add new TOC members.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#191 Move net-{contour,certmanager} to knative-sandbox
  static/golang/net-certmanager.html
  static/golang/net-contour.html
Labels: approved, cla: yes, lgtm, size/XS

#194 Move remaining knative/net-* repositories to knative-sandbox
  static/golang/net-certmanager.html
  static/golang/net-http01.html
  static/golang/net-istio.html
  static/golang/net-kourier.html
Labels: approved, cla: yes, lgtm, size/S

#196 Upgrade Hugo in non-production environments
  netlify.toml
Labels: approved, cla: yes, lgtm, size/XS
