Repository knative/website, pull requests merged in 2020-01, with the labels that each got.

#117 Fix race condition in cookie-consent
  static/js/cookie-consent.js
Labels: approved, cla: yes, lgtm, size/S

#121 release 0.12 updates to site
  config/production/params.toml
  netlify.toml
  scripts/docs-version-settings.sh
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/S

#123 Setup goimports for networking repos
  static/_redirects
  static/golang/net-contour.html
  static/golang/net-istio.html
  static/golang/networking.html
Labels: approved, cla: yes, lgtm, size/S

#119 Move the /community repo content under knative.dev/community
  config/_default/config.toml
  config/_default/params.toml
  layouts/partials/community_links.html
  layouts/partials/landingtoc.html
  layouts/shortcodes/showpartial.html
  scripts/convert-repo-ulrs.sh
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/L

#124 Add the tab[s] shortcodes.
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: approved, cla: yes, lgtm, size/M
