Repository knative/website, pull requests merged in 2020-12, with the labels that each got.

#241 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#242 Update build scripts to build from any named docs fork
  scripts/build.sh
  scripts/docs-version-settings.sh
  scripts/localbuild.sh
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/L

#243 Keep the staging branch up-to-date
  DEVELOPMENT.md
  config/_default/params.toml
  config/local/params.toml
  config/production/params.toml
  config/staging/params.toml
  hack/update-codegen.sh
  netlify.toml
  scripts/build.sh
  scripts/docs-version-settings.sh
  scripts/localbuild.sh
  scripts/processsourcefiles.sh
  static/_redirects
  static/golang/actions-kind.html
  static/golang/kn-plugin-diag.html
  static/golang/kn-plugin-source-pkg.html
  static/golang/knobots.html
  tools/redir-gen/main.go
Labels: approved, cla: yes, lgtm, size/L

#244 Add net-ingressv2 golang redirect
  static/_redirects
  static/golang/net-ingressv2.html
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#245 Fix static HTML build
  scripts/localbuild.sh
Labels: approved, cla: yes, kind/bug, lgtm, size/XS
