Repository knative/website, pull requests merged in 2020-04, with the labels that each got.

#151 Add noopener tags to links
  layouts/blog/baseof.html
  layouts/partials/footer.html
  layouts/partials/page-meta-links.html
Labels: approved, cla: yes, lgtm, size/XS

#156 Add knative.dev/operator go import magic
  static/_redirects
  static/golang/operator.html
Labels: approved, cla: yes, lgtm, size/XS

#157 Add README and DEVELOPMENT instructions
  DEVELOPMENT.md
  README.md
Labels: approved, cla: yes, lgtm, size/M

#160 Add golang redirects for eventing-kafka
  static/_redirects
  static/golang/eventing-kafka.html
Labels: approved, cla: yes, lgtm, size/XS

#161 Don't move 'README.md' over 'index.md', either
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/XS

#159 Update package-lock.json
  package-lock.json
Labels: approved, cla: yes, lgtm, size/L

#168 Update website redirects
  netlify.toml
Labels: approved, cla: yes, lgtm, size/S

#165 Update staging config
  config/staging/params.toml
Labels: approved, cla: yes, lgtm, size/XS

#163 Update params.toml
  config/production/params.toml
Labels: approved, cla: yes, lgtm, size/S

#162 Update params.toml
  config/_default/params.toml
Labels: approved, cla: yes, lgtm, size/XS

#164 Update params.toml
  config/local/params.toml
Labels: approved, cla: yes, lgtm, size/XS

#166 Update default branch config
  scripts/docs-version-settings.sh
Labels: approved, cla: yes, lgtm, size/XS

#169 Working group redirect
  static/_redirects
Labels: approved, cla: yes, lgtm, size/XS
