Repository knative/website, pull requests merged in 2020-02, with the labels that each got.

#127 Add a left border to more clearly delineate the tabs.
  layouts/shortcodes/tabs.html
Labels: approved, cla: yes, lgtm, size/XS

#132 don't make active link bold
  assets/scss/_sidebar-tree.scss
  assets/scss/_variables.scss
Labels: approved, cla: yes, lgtm, size/XS

#130 Bump the version to 0.12
  config/_default/params.toml
  config/local/params.toml
Labels: approved, cla: yes, lgtm, size/XS

#133 minor tab formatting tweaks
  assets/scss/_nav.scss
  layouts/shortcodes/tabs.html
Labels: approved, cla: yes, lgtm, size/S

#129 This adds an artifact shortcode.
  layouts/shortcodes/artifact.html
Labels: approved, cla: yes, lgtm, size/M

#135 use max width even on big screen.
  assets/scss/_nav.scss
  assets/scss/main.scss
Labels: approved, cla: yes, lgtm, size/S

#134 Change font weight to light to make it uniform with the non-nested se…
  assets/scss/_sidebar-tree.scss
Labels: approved, cla: yes, lgtm, size/XS

#136 Add support for a feature-state shortcode
  config/_default/markup.toml
  layouts/shortcodes/feature-state.html
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: approved, cla: yes, lgtm, size/M

#138 Add usage for the tab[s] shortcode.
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: approved, cla: yes, lgtm, size/S

#120 Improve cookie consent to include a "hide" for opting out
  config/_default/params.toml
  content-override/en/about-analytics-cookies.md
  layouts/partials/cookie-consent-modal.html
  layouts/partials/cookie-notice.html
  layouts/partials/footer.html
  static/js/cookie-consent.js
Labels: approved, cla: yes, lgtm, size/L
