Repository knative/website, pull requests merged in 2020-11, with the labels that each got.

#236 Add knative.dev/kn-plugin-source-kafka redirects
  static/_redirects
  static/golang/kn-plugin-source-kafka.html
Labels: approved, cla: yes, lgtm, size/XS

#238 Add knative-sandbox/kn-plugin-diag golang redirect
  static/_redirects
  static/golang/kn-plugin-diag.html
Labels: approved, cla: yes, lgtm, size/XS

#237 Write a tool to automatically fill out the go mod redirects
  static/_redirects
  static/golang/async-component.html
  static/golang/build-spike.html
  static/golang/build.html
  static/golang/client-contrib.html
  static/golang/community.html
  static/golang/docs.html
  static/golang/downstream-test-go.html
  static/golang/eventing-operator.html
  static/golang/homebrew-client.html
  static/golang/integration.html
  static/golang/observability.html
  static/golang/sample-controller.html
  static/golang/serving-operator.html
  static/golang/website.html
  static/golang/wg-repository.html
  tools/redir-gen/go.mod
  tools/redir-gen/go.sum
  tools/redir-gen/main.go
  tools/redir-gen/redirtemplate.gohtml
Labels: approved, cla: yes, lgtm, size/L

#233 Fix mac errors for local server
  scripts/localbuild.sh
Labels: approved, cla: yes, lgtm, size/M

#239 Add an update-codegen to regenerate the static redirects.
  hack/update-codegen.sh
  static/_redirects
  static/golang/actions-kind.html
  static/golang/kn-plugin-diag.html
  static/golang/kn-plugin-source-pkg.html
  static/golang/knobots.html
  tools/redir-gen/main.go
Labels: approved, cla: yes, lgtm, size/M

#240 update docs build for 0.19
  config/_default/params.toml
  config/local/params.toml
  config/production/params.toml
  config/staging/params.toml
  netlify.toml
  scripts/docs-version-settings.sh
Labels: approved, cla: yes, lgtm, size/M
