Repository knative/website, pull requests merged in 2020-08, with the labels that each got.

#195 add eventing-autoscaler-keda redirect
  static/_redirects
  static/golang/eventing-autoscaler-keda.html
Labels: approved, cla: yes, lgtm, size/XS

#199 Update npm dependencies
  package-lock.json
  package.json
Labels: approved, cla: yes, lgtm, size/XL

#197 Switch to static build
  DEVELOPMENT.md
  scripts/localbuild.sh
Labels: approved, cla: yes, lgtm, size/L

#200 Upgrade to Hugo 0.74.3, fix knative/docs#2706
  netlify.toml
Labels: approved, cla: yes, lgtm, size/XS

#202 Black Lives Matter announcement
  assets/scss/_nav.scss
  layouts/partials/hooks/head-end.html
  layouts/partials/navbar.html
  static/js/script.js
Labels: approved, cla: yes, lgtm, size/M

#203 update build files for release 0.17
  config/_default/params.toml
  config/local/params.toml
  config/production/params.toml
  config/staging/params.toml
  netlify.toml
  scripts/docs-version-settings.sh
  scripts/processsourcefiles.sh
Labels: approved, cla: yes, lgtm, size/M

#205 new async repo updates
  static/_redirects
  static/golang/async-component.html
Labels: approved, cla: yes, lgtm, size/XS
