Repository knative/website, pull requests merged in 2020-09, with the labels that each got.

#206 adding reconciler-test repo to website
  static/_redirects
  static/golang/reconciler-test.html
Labels: approved, cla: yes, lgtm, size/XS

#207 Remove master references where possible.
  config/_default/params.toml
  layouts/partials/navbar-version-selector.html
  layouts/partials/navbar.html
  layouts/partials/page-meta-links.html
  layouts/shortcodes/artifact.html
  layouts/shortcodes/version.md
Labels: approved, cla: yes, lgtm, size/M

#210 Redirects to github.com/knative-sandbox/XXX for eventing-contrib repos
  static/_redirects
  static/golang/eventing-awssqs.html
  static/golang/eventing-camel.html
  static/golang/eventing-ceph.html
  static/golang/eventing-couchdb.html
  static/golang/eventing-github.html
  static/golang/eventing-gitlab.html
  static/golang/eventing-natss.html
  static/golang/eventing-prometheus.html
Labels: approved, cla: yes, lgtm, size/M

#211 fix github repo links
  layouts/partials/page-meta-links.html
Labels: approved, cla: yes, lgtm, size/S

#213 natss got missed on the pasta
  static/golang/eventing-natss.html
Labels: approved, cla: yes, lgtm, size/XS

#215 fix redirects to knative-sandbox
  static/golang/eventing-camel.html
  static/golang/eventing-ceph.html
  static/golang/eventing-couchdb.html
  static/golang/eventing-github.html
  static/golang/eventing-gitlab.html
  static/golang/eventing-prometheus.html
Labels: approved, cla: yes, lgtm, size/S

#214 Add knative.dev/kperf golang redirect
  static/_redirects
  static/golang/kperf.html
Labels: approved, cla: yes, lgtm, size/XS

#212 Move hidden files
  config/_default/config.toml
Labels: approved, cla: yes, lgtm, size/XS

#216 Add release-0.18 to build
  config/_default/params.toml
  config/local/params.toml
  config/production/params.toml
  config/staging/params.toml
  netlify.toml
  scripts/docs-version-settings.sh
Labels: approved, cla: yes, lgtm, size/S
