Repository knative/website, pull requests merged in 2021-05, with the labels that each got.

#288 Enable new "help" section and fix a few things
  DEVELOPMENT.md
  config/_default/config.toml
  config/_default/params.toml
  i18n/en.toml
  layouts/partials/community_links.html
  layouts/partials/page-meta-links.html
  scripts/convert-repo-ulrs.sh
  scripts/localbuild.sh
  scripts/processsourcefiles.sh
  static/_redirects
Labels: approved, cla: yes, lgtm, size/L

#295 Remove golang module and build scripts from hugo build
  config/_default/config.toml
Labels: approved, cla: yes, lgtm, size/XS

#298 [Automated] Fix misspellings
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#297 Update the Staging branch
  DEVELOPMENT.md
  Gemfile
  OWNERS
  OWNERS_ALIASES
  assets/scss/_code.scss
  config/_default/config.toml
  config/_default/params.toml
  config/local/params.toml
  config/production/params.toml
  config/staging/params.toml
  i18n/en.toml
  layouts/partials/community_links.html
  layouts/partials/page-meta-links.html
  netlify.toml
  package-lock.json
  scripts/build.sh
  scripts/convert-repo-ulrs.sh
  scripts/docs-version-settings.sh
  scripts/localbuild.sh
  scripts/processsourcefiles.sh
  static/_redirects
Labels: approved, cla: yes, lgtm, size/XL

#302 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#301 [main] Upgrade to latest dependencies
  static/golang/actions-downstream-test.html
  static/golang/homebrew-kn-plugins.html
Labels: approved, cla: yes, lgtm, size/XS

#303 update website for v0.23
  config/_default/params.toml
  config/local/params.toml
  config/production/params.toml
  config/staging/params.toml
  netlify.toml
  scripts/docs-version-settings.sh
Labels: approved, cla: yes, lgtm, size/M

#300 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#306 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#307 redirect development to new mkdocs
  netlify.toml
  scripts/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#305 [main] Upgrade to latest dependencies
  static/golang/docs.html
Labels: approved, cla: yes, lgtm, size/XS

#309 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S
