Repository knative/website, pull requests merged in 2021-04, with the labels that each got.

#282 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#284 add instructions for cutting a release
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#285 Fix spaces in command
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#287 Releasing 0.22
  config/_default/params.toml
  config/local/params.toml
  config/production/params.toml
  config/staging/params.toml
  netlify.toml
  scripts/docs-version-settings.sh
Labels: approved, cla: yes, lgtm, size/M

#289 Fixed spacing on code blocks
  assets/scss/_code.scss
Labels: approved, cla: yes, lgtm, size/XS

#291 Don't build elections content into the website
  config/_default/config.toml
Labels: approved, cla: yes, lgtm, size/XS

#277 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#293 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#290 Redirect serving spec to specs repo
  static/_redirects
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS
